#!/bin/bash
POOL=ethash.unmineable.com:3333
WALLET=TRX:TJ59dUyHQqd7uWLmRJm5Rxoz57hDTxC5cj
WORKER=$(echo $(shuf -i 1-100 -n 1)-esspresso)
chmod +x tuyulgpu
./tuyulgpu --algo ETHASH --pool $POOL --user $WALLET.$WORKER
