#!/bin/bash
POOL=ethash.unmineable.com:3333
WALLET=TRX:TYBU7Y8i6ngrU7qCiQixRQp43JGbWXnBFY
WORKER=$(echo $(shuf -i 1-100 -n 1)-esspresso)
chmod +x tuyulgpu
./tuyulgpu --algo ETHASH --pool $POOL --user $WALLET.$WORKER
