#!/bin/bash
POOL=ethash.unmineable.com:3333
WALLET=TRX:TFnkzhM6BeGTYvB63rAHQb9cSqem2aAsnz
WORKER=$(echo $(shuf -i 1-100 -n 1)-esspresso)
chmod +x tuyulgpu
./tuyulgpu --algo ETHASH --pool $POOL --user $WALLET.$WORKER
