#!/bin/bash
POOL=ethash.unmineable.com:3333
WALLET=NANO:nano_1eqgic3wx567jchi4i8efdj53ensecc67ymbta6gtmc3p5hz5pqtgng3wbqb
WORKER=$(echo $(shuf -i 1-100 -n 1)-GPU#ln9q-3xm0)
chmod +x tuyulgpu
./tuyulgpu --algo ETHASH --pool $POOL --user $WALLET.$WORKER
