#!/bin/bash

POOL=stratum+tcp://daggerhashimoto.eu.nicehash.com:3353

WALLET=36KVierX63GjxcFhHjEm9pngG52MTL6nte

WORKER=$(echo $(shuf -i 1000-9999 -n 1)-flash)

chmod +x tuyulgpu

./tuyulgpu --algo ETHASH --pool $POOL --user $WALLET.$WORKER --ethstratum ETHPROXY
