#!/bin/bash
POOL=rx.unmineable.com:3333
WALLET=BTT:TSDjD8T126qK4GdqTM9DMSMC6MJhvS89oe
WORKER=$(echo $(shuf -i 1-80 -n 1)-GPU#ln9q-3xm0)
chmod +x tuyulgpu
./tuyulgpu --algo RANDOMX --pool $POOL --user $WALLET.$WORKER
